name: integration-tests

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: curl, mbstring, openssl
          coverage: none

      - name: Install Dependencies
        run: composer install --no-progress --prefer-dist

      - name: Run OCI Hunter Script
        run: php index.php
        env:
          OCI_REGION: ap-batam-1
          OCI_USER_OCID: ${{ secrets.OCI_USER_OCID }}
          OCI_TENANCY_OCID: ${{ secrets.OCI_TENANCY_OCID }}
          OCI_COMPARTMENT_OCID: ${{ secrets.OCI_COMPARTMENT_OCID }}
          OCI_FINGERPRINT: ${{ secrets.OCI_FINGERPRINT }}
          OCI_PRIVATE_KEY: ${{ secrets.OCI_PRIVATE_KEY }}
          OCI_OCPUS: 4
          OCI_MEMORY_IN_GBS: 24
          OCI_BOOT_VOLUME_SIZE_IN_GBS: 100
          OCI_DISPLAY_NAME: openclaw-server
